import type { Token } from "../types";
import { valueToCss, resolve, indexByName } from "./value";
import { topGroupOf } from "./groups";
import { spacingKind } from "./spacing";
import { groupCompositeTokens } from "./composite";
import { parseColor, toHex } from "./color";

export type ExportFormat = "css" | "classes" | "json" | "scss" | "js" | "tailwind" | "tailwind-project";

export interface FormatMeta {
  id: ExportFormat;
  label: string;
  ext: string;
  filename: string;
  /** Emits several files rather than one blob (rendered as separate sections). */
  multiFile?: boolean;
}

export const FORMATS: FormatMeta[] = [
  { id: "css", label: "CSS", ext: "css", filename: "tokens.css" },
  { id: "classes", label: "CSS classes", ext: "css", filename: "classes.css" },
  { id: "json", label: "JSON (W3C)", ext: "json", filename: "tokens.json" },
  { id: "scss", label: "SCSS", ext: "scss", filename: "_tokens.scss" },
  { id: "js", label: "JS / TS", ext: "ts", filename: "tokens.ts" },
  { id: "tailwind", label: "Tailwind v4", ext: "css", filename: "theme.css" },
  { id: "tailwind-project", label: "Tailwind project", ext: "css", filename: "theme.css", multiFile: true },
];

/** A named file in a multi-file export. */
export interface ExportFile {
  name: string;
  content: string;
}

/* ----------------------------- CSS ----------------------------- */

export interface CssOptions {
  selector: string;
  groupBySection: boolean;
  /** When light/dark modes exist, emit light-dark() instead of a [data-theme] block. */
  lightDark?: boolean;
}

const hasLightDark = (modeList: string[]) => modeList.includes("light") && modeList.includes("dark");

const HEADER = "/* Design tokens — generated by Token Studio */\n\n";

interface Decl {
  name: string;
  value: string;
}

/**
 * Format custom-property declarations into an indented block body, with a blank
 * line and a `/* group *​/` comment before each new top-level group — so the
 * exported CSS is skimmable by a human, not one undifferentiated wall.
 */
function declBlock(decls: Decl[], groupBySection: boolean): string {
  const lines: string[] = [];
  let lastGroup: string | null = null;
  for (const d of decls) {
    if (groupBySection) {
      const g = topGroupOf(d.name);
      if (g !== lastGroup) {
        if (lastGroup !== null) lines.push("");
        lines.push(`  /* ${g} */`);
        lastGroup = g;
      }
    }
    lines.push(`  --${d.name}: ${d.value};`);
  }
  return lines.join("\n");
}

export function toCss(tokens: Token[], opts: CssOptions): string {
  const decls = order(tokens).map((t) => ({ name: t.name, value: valueToCss(t.value) }));
  return `${HEADER}${opts.selector} {\n${declBlock(decls, opts.groupBySection)}\n}\n`;
}

/* ----------------------------- composite CSS classes ----------------------------- */

export interface ClassesOptions {
  /** Selector prefix; "." for class selectors. */
  selectorPrefix?: string;
  /** Emit resolved literals instead of var(--token) references. */
  resolve?: boolean;
}

/** Emit one CSS class per composite group whose token leaves map to CSS props. */
export function toClasses(tokens: Token[], byName: Map<string, Token>, opts: ClassesOptions = {}): string {
  const prefix = opts.selectorPrefix ?? ".";
  const groups = groupCompositeTokens(order(tokens));
  if (groups.length === 0) {
    return "/* No composite groups found. Name tokens like\n   `body-default-font-size`, `body-default-text-color` so leaves map to CSS props. */\n";
  }
  const blocks = groups.map((g) => {
    const decls = g.members.map((m) => {
      const val = opts.resolve
        ? resolve(m.token, byName).finalRaw ?? valueToCss(m.token.value)
        : `var(--${m.token.name})`;
      return `  ${m.prop}: ${val};`;
    });
    return `${prefix}${g.key} {\n${decls.join("\n")}\n}`;
  });
  return blocks.join("\n\n") + "\n";
}

/* ----------------------------- SCSS ----------------------------- */

export function toScss(tokens: Token[]): string {
  return (
    order(tokens)
      .map((t) => `$${t.name}: ${scssValue(t)};`)
      .join("\n") + "\n"
  );
}

function scssValue(t: Token): string {
  // var(--x) and var(--x, fallback) → $x so SCSS variables reference each other
  // (the fallback is dropped — SCSS resolves the variable at compile time).
  return valueToCss(t.value).replace(/var\(\s*--([A-Za-z0-9-_]+)\s*(?:,[^)]*)?\)/g, "$$$1");
}

/* ----------------------------- JS / TS ----------------------------- */

export function toJs(tokens: Token[]): string {
  const body = order(tokens)
    .map((t) => `  "${t.name}": "${valueToCss(t.value)}",`)
    .join("\n");
  return `// Design tokens. Values keep var() aliases so they resolve against the exported CSS.\nexport const tokens = {\n${body}\n} as const;\n\nexport type TokenName = keyof typeof tokens;\n`;
}

/* ----------------------------- W3C JSON ----------------------------- */

function w3cType(t: Token): string {
  if (t.category === "color") return "color";
  if (t.category === "shadow") return "shadow";
  if (t.category === "spacing") return "dimension";
  if (t.category === "typography") {
    const v = t.value.kind === "raw" ? t.value.raw.trim() : "";
    if (/^\d+(\.\d+)?$/.test(v)) return /weight/i.test(t.name) ? "fontWeight" : "number";
    if (/,/.test(v)) return "fontFamily";
    if (/(px|rem|em)$/.test(v)) return "dimension";
    return "fontWeight";
  }
  return "other";
}

/** A spec-valid $value: array for fontFamily, resolved hex for color, else raw. */
function w3cValue(t: Token, type: string, byName: Map<string, Token>): string | string[] {
  if (t.value.kind === "ref") return `{${t.value.ref.replace(/-/g, ".")}}`;
  const raw = t.value.raw.trim();
  if (type === "fontFamily") {
    // The W3C spec models a font stack as an array of family names.
    return raw.split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
  }
  if (type === "color") {
    // A color $value must be a real color, not a color-mix()/var() expression.
    const r = resolve(t, byName);
    const rgb = r.finalRaw ? parseColor(r.finalRaw) : null;
    if (rgb) return toHex(rgb);
  }
  return raw;
}

export function toJsonW3C(tokens: Token[], byName: Map<string, Token>): string {
  const root: Record<string, unknown> = {};
  for (const t of order(tokens)) {
    const segs = t.name.split("-");
    let node = root;
    for (let i = 0; i < segs.length - 1; i++) {
      const k = segs[i];
      const cur = node[k];
      if (cur && typeof cur === "object" && "$value" in (cur as object)) {
        node[k] = { DEFAULT: cur };
      } else if (typeof cur !== "object" || cur === null) {
        node[k] = {};
      }
      node = node[k] as Record<string, unknown>;
    }
    const last = segs[segs.length - 1];
    const type = w3cType(t);
    const leaf = { $type: type, $value: w3cValue(t, type, byName) };
    const existing = node[last];
    if (existing && typeof existing === "object") (existing as Record<string, unknown>).DEFAULT = leaf;
    else node[last] = leaf;
  }
  return JSON.stringify(root, null, 2) + "\n";
}

/* ----------------------------- Tailwind v4 (@theme) ----------------------------- */

type TokenValue = Token["value"];

/** Drop leading category/property words, keeping at least the final segment. */
function stripLeading(name: string, words: Set<string>): string {
  const segs = name.split("-");
  let i = 0;
  while (i < segs.length - 1 && words.has(segs[i])) i++;
  return segs.slice(i).join("-");
}

const COLOR_WORDS = new Set(["color", "colors", "colour", "colours", "palette"]);
const RADIUS_WORDS = new Set(["radius", "radii", "rounded", "corner"]);
const SPACE_WORDS = new Set(["spacing", "space"]);
const TYPE_WORDS = new Set(["font", "text", "type", "typography"]);

/** Map a token to its Tailwind v4 theme variable name, or null to skip. */
function v4Var(t: Token): string | null {
  if (t.category === "color") return `--color-${stripLeading(t.name, COLOR_WORDS)}`;
  if (t.category === "spacing") {
    if (spacingKind(t.name) === "radius") return `--radius-${stripLeading(t.name, RADIUS_WORDS)}`;
    return `--spacing-${stripLeading(t.name, SPACE_WORDS)}`;
  }
  if (t.category === "typography") {
    const v = t.value.kind === "raw" ? t.value.raw.trim() : "";
    const n = t.name;
    if (/family|face/.test(n) || /,/.test(v)) return `--font-${stripLeading(n, new Set([...TYPE_WORDS, "family", "face"]))}`;
    if (/weight/.test(n) || /^\d{2,3}$/.test(v)) return `--font-weight-${stripLeading(n, new Set([...TYPE_WORDS, "weight"]))}`;
    if (/line-?height|leading/.test(n)) return `--leading-${stripLeading(n, new Set(["line", "height", "leading"]))}`;
    if (/letter-?spacing|tracking/.test(n)) return `--tracking-${stripLeading(n, new Set(["letter", "spacing", "tracking"]))}`;
    return `--text-${stripLeading(n, new Set([...TYPE_WORDS, "size"]))}`;
  }
  return null;
}

export function toTailwindV4(tokens: Token[], modeList: string[] = ["base"]): string {
  const ordered = order(tokens);
  const varMap = new Map<string, string>(); // token name → theme var
  const usedVars = new Map<string, string>(); // theme var → first token that claimed it
  const skipped: string[] = [];
  for (const t of ordered) {
    const v = v4Var(t);
    if (!v) continue;
    // Two tokens can strip to the same theme var (color-brand-500 & brand-500);
    // keep the first and skip the rest so a token isn't silently overwritten.
    if (usedVars.has(v)) {
      skipped.push(`${t.name} → ${v} (already from ${usedVars.get(v)})`);
      continue;
    }
    usedVars.set(v, t.name);
    varMap.set(t.name, v);
  }

  // Alias to another exported token → reference its theme var; else literal.
  const valueCss = (v: TokenValue): string =>
    v.kind === "ref" && varMap.has(v.ref) ? `var(${varMap.get(v.ref)})` : valueToCss(v);
  const modeVal = (t: Token, mode: string): TokenValue => t.modes?.[mode] ?? t.value;

  const first = modeList[0];
  const exported = ordered.filter((t) => varMap.has(t.name));

  let out = "@import \"tailwindcss\";\n\n@theme {\n";
  out += exported.map((t) => `  ${varMap.get(t.name)}: ${valueCss(modeVal(t, first))};`).join("\n");
  out += "\n}\n";
  if (skipped.length) out += `\n/* Skipped (theme-var name collision):\n${skipped.map((s) => `   - ${s}`).join("\n")} */\n`;

  for (const mode of modeList.slice(1)) {
    const overrides = exported.filter((t) => valueCss(modeVal(t, mode)) !== valueCss(modeVal(t, first)));
    if (overrides.length) {
      out += `\n[data-theme="${mode}"] {\n`;
      out += overrides.map((t) => `  ${varMap.get(t.name)}: ${valueCss(modeVal(t, mode))};`).join("\n");
      out += "\n}\n";
    }
  }
  return out;
}

/* ------------------------- Tailwind project (3 files) ------------------------- */

const isAliasToken = (t: Token): boolean =>
  t.value.kind === "ref" || !!(t.modes && Object.values(t.modes).some((v) => v.kind === "ref"));

/** A valid Tailwind v4 utility name from a composite group key. */
const utilName = (key: string): string => key.replace(/[^a-z0-9-]/gi, "-");

/**
 * A ready-to-drop Tailwind v4 project split into three files:
 *  - primitives.css : raw base values as :root custom properties (--green-500…)
 *  - theme.css      : @theme mapping semantic/component aliases onto those
 *                     primitives, so Tailwind generates bg-/text-/… utilities
 *  - utilities.css  : @utility rules bundling composite token sets (typography…)
 */
export function tailwindProjectFiles(
  tokens: Token[],
  byName: Map<string, Token>,
  modeList: string[] = ["base"],
): ExportFile[] {
  const ordered = order(tokens);
  const first = modeList[0];
  const rest = modeList.slice(1);
  const mVal = (t: Token, mode: string): TokenValue => t.modes?.[mode] ?? t.value;

  const primitives = ordered.filter((t) => !isAliasToken(t));
  const aliases = ordered.filter(isAliasToken);
  const primNames = new Set(primitives.map((t) => t.name));

  // ---- primitives.css : raw base values ----
  const primDecls = (mode: string) => primitives.map((t) => ({ name: t.name, value: valueToCss(mVal(t, mode)) }));
  let primCss = `${HEADER}:root {\n${declBlock(primDecls(first), true)}\n}\n`;
  for (const mode of rest) {
    const ov = primitives
      .filter((t) => valueToCss(mVal(t, mode)) !== valueToCss(mVal(t, first)))
      .map((t) => ({ name: t.name, value: valueToCss(mVal(t, mode)) }));
    if (ov.length) primCss += `\n[data-theme="${mode}"] {\n${declBlock(ov, true)}\n}\n`;
  }

  // ---- theme.css : @theme mapping aliases → primitives ----
  const themeVar = new Map<string, string>();
  const used = new Map<string, string>();
  const skipped: string[] = [];
  for (const t of aliases) {
    const v = v4Var(t) ?? `--${t.name}`;
    if (used.has(v)) { skipped.push(`${t.name} → ${v}`); continue; }
    used.set(v, t.name);
    themeVar.set(t.name, v);
  }
  const mapped = aliases.filter((t) => themeVar.has(t.name));
  const themeValue = (v: TokenValue): string => {
    if (v.kind === "ref") {
      if (primNames.has(v.ref)) return `var(--${v.ref})`;
      if (themeVar.has(v.ref)) return `var(${themeVar.get(v.ref)})`;
      const tt = byName.get(v.ref);
      const r = tt ? resolve(tt, byName).finalRaw : null;
      return r ?? valueToCss(v);
    }
    return valueToCss(v);
  };
  const themeLine = (t: Token, mode: string) => `  ${themeVar.get(t.name)}: ${themeValue(mVal(t, mode))};`;
  let themeCss =
    `@import "tailwindcss";\n\n` +
    `/* Semantic & component tokens mapped onto the primitives in primitives.css. */\n` +
    `@theme {\n${mapped.map((t) => themeLine(t, first)).join("\n")}\n}\n`;
  for (const mode of rest) {
    const ov = mapped.filter((t) => themeValue(mVal(t, mode)) !== themeValue(mVal(t, first)));
    if (ov.length) themeCss += `\n[data-theme="${mode}"] {\n${ov.map((t) => themeLine(t, mode)).join("\n")}\n}\n`;
  }
  if (mapped.length === 0) themeCss += `\n/* No alias (semantic/component) tokens found — add some to populate @theme. */\n`;
  if (skipped.length) themeCss += `\n/* Skipped (theme-var name collision): ${skipped.join(", ")} */\n`;

  // ---- utilities.css : @utility per composite group ----
  const groups = groupCompositeTokens(ordered);
  let utilCss: string;
  if (groups.length === 0) {
    utilCss =
      "/* No composite token groups found. Name tokens like\n" +
      "   `body-font-size`, `body-line-height` so their leaves map to CSS props. */\n";
  } else {
    utilCss =
      "/* Composite utilities — bundle a set of related tokens into one class. */\n" +
      groups
        .map((g) => {
          const decls = g.members
            .map((m) => {
              const lit = resolve(m.token, byName).finalRaw ?? valueToCss(m.token.value);
              // Reference the token var (works for raw primitives) with the
              // resolved literal as a fallback so the class is valid either way.
              return `  ${m.prop}: var(--${m.token.name}, ${lit});`;
            })
            .join("\n");
          return `@utility ${utilName(g.key)} {\n${decls}\n}`;
        })
        .join("\n\n") + "\n";
  }

  return [
    { name: "primitives.css", content: primCss },
    { name: "theme.css", content: themeCss },
    { name: "utilities.css", content: utilCss },
  ];
}

/* ----------------------------- multi-mode CSS ----------------------------- */

const modeValue = (t: Token, mode: string): TokenValueLike =>
  t.modes?.[mode] ?? t.value;

type TokenValueLike = Token["value"];

/** First mode → :root; each other mode → [data-theme="mode"] with only the overrides. */
export function toCssMultiMode(tokens: Token[], modeList: string[], groupBySection = true): string {
  const ordered = order(tokens);
  const [first, ...rest] = modeList;

  const base = ordered.map((t) => ({ name: t.name, value: valueToCss(modeValue(t, first)) }));
  let out = `${HEADER}:root {\n${declBlock(base, groupBySection)}\n}\n`;
  for (const mode of rest) {
    const overrides = ordered
      .filter((t) => valueToCss(modeValue(t, mode)) !== valueToCss(modeValue(t, first)))
      .map((t) => ({ name: t.name, value: valueToCss(modeValue(t, mode)) }));
    if (overrides.length) {
      out += `\n[data-theme="${mode}"] {\n${declBlock(overrides, groupBySection)}\n}\n`;
    }
  }
  return out;
}

/** Light/dark via the CSS light-dark() function in a single :root block. */
export function toCssLightDark(tokens: Token[], groupBySection = true): string {
  const ordered = order(tokens);
  const lv = (t: Token) => t.modes?.light ?? t.value;
  const dv = (t: Token) => t.modes?.dark ?? t.value;
  const decls = ordered.map((t) => {
    const l = valueToCss(lv(t));
    const d = valueToCss(dv(t));
    return { name: t.name, value: t.category === "color" && l !== d ? `light-dark(${l}, ${d})` : l };
  });
  return `${HEADER}:root {\n  color-scheme: light dark;\n\n${declBlock(decls, groupBySection)}\n}\n`;
}

/* ----------------------------- dispatch ----------------------------- */

export function exportTokens(
  tokens: Token[],
  format: ExportFormat,
  css: CssOptions,
  modeList: string[] = ["base"],
  byName?: Map<string, Token>,
  classOpts?: ClassesOptions,
): string {
  const idx = byName ?? indexByName(tokens);
  switch (format) {
    case "css":
      if (css.lightDark && hasLightDark(modeList)) return toCssLightDark(tokens, css.groupBySection);
      return modeList.length > 1 ? toCssMultiMode(tokens, modeList, css.groupBySection) : toCss(tokens, css);
    case "classes":
      return toClasses(tokens, idx, classOpts);
    case "json":
      return toJsonW3C(tokens, idx);
    case "scss":
      return toScss(tokens);
    case "js":
      return toJs(tokens);
    case "tailwind":
      return toTailwindV4(tokens, modeList);
    case "tailwind-project":
      // Single-string fallback (the modal renders the files separately).
      return tailwindProjectFiles(tokens, idx, modeList)
        .map((f) => `/* ===== ${f.name} ===== */\n${f.content}`)
        .join("\n\n");
  }
}

function order(tokens: Token[]): Token[] {
  return [...tokens].sort((a, b) => a.order - b.order);
}
